# Generated by Django 5.0.7 on 2024-10-03 17:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0009_expenses_cash_box_income_cash_box'),
        ('registration', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='cash_boxes',
            field=models.ManyToManyField(to='main.cash_box'),
        ),
    ]
