# Generated by Django 5.0.7 on 2024-10-03 17:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0002_customuser_cash_boxes'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='cash_boxes',
        ),
    ]
