# Generated by Django 5.0.7 on 2024-10-03 17:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0009_expenses_cash_box_income_cash_box'),
        ('registration', '0003_remove_customuser_cash_boxes'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='cash_boxes',
            field=models.ManyToManyField(related_name='users', to='main.cash_box'),
        ),
    ]
