# Generated by Django 5.0.7 on 2024-07-28 15:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='expenses',
            old_name='user_id',
            new_name='user',
        ),
        migrations.RenameField(
            model_name='income',
            old_name='user_id',
            new_name='user',
        ),
    ]
