# Generated by Django 5.0.7 on 2024-09-13 12:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_rename_user_id_expenses_user_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='subcategory',
            name='category_id',
            field=models.ForeignKey(default=-1, on_delete=django.db.models.deletion.PROTECT, to='main.category'),
            preserve_default=False,
        ),
    ]
