# Generated by Django 5.0.7 on 2024-09-13 12:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_subcategory_category_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='subcategory',
            old_name='category_id',
            new_name='category',
        ),
    ]
