# Generated by Django 5.0.7 on 2024-09-28 17:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_rename_category_id_subcategory_category'),
    ]

    operations = [
        migrations.CreateModel(
            name='Expenses_statistic',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.FloatField()),
                ('percentage', models.FloatField()),
                ('count_of_transactions', models.IntegerField()),
                ('average_transaction', models.FloatField()),
                ('last_transaction', models.CharField(max_length=255, null=True)),
                ('max_transaction', models.CharField(max_length=255, null=True)),
                ('min_transaction', models.CharField(max_length=255, null=True)),
                ('monthly_difference', models.FloatField()),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='main.category')),
            ],
        ),
    ]
