# Generated by Django 5.0.7 on 2024-10-03 16:37

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0008_cash_box'),
    ]

    operations = [
        migrations.AddField(
            model_name='expenses',
            name='cash_box',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='main.cash_box'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='income',
            name='cash_box',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='main.cash_box'),
            preserve_default=False,
        ),
    ]
