# Generated by Django 5.0.7 on 2024-10-04 14:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0010_budget'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='budget',
            name='category',
        ),
    ]
