# Generated by Django 5.0.7 on 2024-10-06 11:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0011_remove_budget_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='budget',
            name='fixed',
            field=models.BooleanField(default=True),
            preserve_default=False,
        ),
    ]
