# Generated by Django 5.0.7 on 2024-10-15 16:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0012_budget_fixed'),
    ]

    operations = [
        migrations.AddField(
            model_name='cash_box',
            name='active_image',
            field=models.FileField(blank=True, null=True, upload_to='svg_images/'),
        ),
        migrations.AddField(
            model_name='cash_box',
            name='color',
            field=models.CharField(blank=True, max_length=8, null=True),
        ),
        migrations.AddField(
            model_name='cash_box',
            name='default_image',
            field=models.FileField(blank=True, null=True, upload_to='svg_images/'),
        ),
    ]
