# Generated by Django 5.0.7 on 2024-10-15 17:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0013_cash_box_active_image_cash_box_color_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cash_box',
            name='active_image',
            field=models.FileField(blank=True, null=True, upload_to='svg_images/cashbox_logo'),
        ),
        migrations.AlterField(
            model_name='cash_box',
            name='default_image',
            field=models.FileField(blank=True, null=True, upload_to='svg_images/cashbox_logo'),
        ),
    ]
